### ISSUE TITLE
能否提供设置会话的方法呢？

### ISSUE THREAD

**Issue by thinkive** [Dongss/koa-socketio-session#1]
目前貌似只提供了获得会话的方法。

**Comment by Dongss** [comment]
我正在写，目标是`socket.session`达成和koa `ctx.session`一样的设置和获取session方法，预计本周能完工

**Comment by Dongss** [comment]
https://stackoverflow.com/questions/39191517/set-cookie-inside-websocket-connection

koa 的 session 中间件都是实现了设置session(如果没有就初始化一个)，并设置cookie，websocket是无法在server端设置cookie的， 所以这里决定不实现。

自己做可以在客户端设置cookie，需要修改session的时候使用 koa session 中间件的 `store.set()` 方法设置session

**Comment by thinkive** [comment]
你的意思是，我在服务器端先获得会话ID，然后客户端在建立socket连接后，将服务器获得的会话id,在客户端设置到cookie中，然后再koa session去实现store.set0方法，这样就可以修改会话吗？

**Comment by Dongss** [comment]
是的
