### ISSUE TITLE
koa default key has changed in 6.x

### ISSUE THREAD

**Issue by AoDev** [Dongss/koa-socketio-session#2]
Hello, 

__koa has changed the default key from `koa:sess` to `koa.sess`.__

> 6.x changed the default cookie key from koa:sess to koa.sess to ensure set-cookie value valid with HTTP spec.see issue. If you want to be compatible with the previous version, you can manually set config.key to koa:sess.

[readme link](https://github.com/koajs/session#notice)

The fallback in the code is not completely valid from 6.x, like [here](https://github.com/Dongss/koa-socketio-session/blob/master/src/index.ts#L44)

**Comment by Dongss** [comment]
Thank you!  I will notice this in the document.
